version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./hackrx_db.db
    volumes:
      - .:/app
      - sqlite_data:/app/data
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload

volumes:
  sqlite_data: