[phases.setup]
nixPkgs = ['python311']

[phases.install]
cmds = [
    'pip install -r requirements-railway.txt'
]

[phases.build]
cmds = [
    'echo "Build phase complete"'
]

[start]
cmd = 'uvicorn app_railway:app --host 0.0.0.0 --port $PORT'