[build]
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "python -m uvicorn app:app --host 0.0.0.0 --port 8000 --workers 1"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[variables]
PORT = "8000"